### ISSUE TITLE
A Database Error Occurred  - Error Number: 1146

### ISSUE THREAD

**Issue by Elmeromoto** [CareersSkillsIncubator/menteer#2]
After setting up and following the instructions in the readme I'm now running into the following error:

```
A Database Error Occurred

Error Number: 1146

Table '(database name).content' doesn't exist

SELECT * FROM content WHERE id != ''

Filename: models/Application_model.php

Line Number: 73
```

Manually creating that table in the database moves me onto a separate error:

```
Error Number: 1054

Unknown column 'id' in 'where clause'

SELECT * FROM content WHERE id != ''

Filename: models/Application_model.php

Line Number: 73
```

I'm not very familiar with SQL, so maybe you might have some insight on this issue that could help me get my own clone of your platform running.  Any ideas?

**Comment by hamiltonmascioli** [comment]
import this file into your mysql database or since its small add the
structure and content manuall. Must have these id's and content for the
homepage to appear but you can edit this in the controller/view after and
remove.

Best,
Jason

**Comment by Elmeromoto** [comment]
Which file?  I think you maybe forgot to attach it.

**Comment by hamiltonmascioli** [comment]
[936640_menteer_2016-03-21.sql.gz](https://github.com/CareersSkillsIncubator/menteer/files/182710/936640_menteer_2016-03-21.sql.gz)

**Comment by Elmeromoto** [comment]
That did the trick.  Thanks!
